### ISSUE TITLE
first estimate of mdfnn function

### ISSUE THREAD

**Issue by Wallot** [morenococo/crqa#15]
The first estimate for the embedding parameter in the mdfnn function is fixed to 100%. However, it needs to change contingent on the data structure.

**Comment by racdale** [comment]
Would this correspond to an update on line 80 of [mdFnn.R](https://github.com/morenococo/crqa/blob/master/R/mdFnn.R)...

`fnnPerc = 100       # first FNN`

...to correspond to line 119 on the original MATLAB source for mdembedding [here](https://github.com/danm0nster/mdembedding/blob/master/mdFnn.m)?

`fnnPerc = zeros(maxEmb-1,1); % first FNN`

**Comment by morenococo** [comment]
Accepted your change @Wallot . implemented and tested in the latest version of crqa_2.0.6
