### ISSUE TITLE
Potential issues with embedding dimension estimates in `optimizeParam()`

### ISSUE THREAD

**Issue by a-paxton** [morenococo/crqa#17]
Hi there,

In the `optimizeParam()` function, it appears that the `false.nearest()` calls use a hard-coded delay of `1` ...

> https://github.com/morenococo/crqa/blob/08fd898a1322815d4c24adbe075eb2617ef15669/R/optimizeParam.R#L132
> 
> https://github.com/morenococo/crqa/blob/08fd898a1322815d4c24adbe075eb2617ef15669/R/optimizeParam.R#L159
> 

... even though the code has already found the data-driven delay earlier in the code:

> https://github.com/morenococo/crqa/blob/08fd898a1322815d4c24adbe075eb2617ef15669/R/optimizeParam.R#L109

In addition, the same calls use a hard-coded maximum embedding dimension of `20` (see same lines above), even though it's included as a user-specified parameter.

I propose a fix that incorporates the identified optimal delay and (if it exists) the user-specified maximum embedding dimension.

Thanks!

**Comment by morenococo** [comment]
I followed the suggestion, tested, and fixed as indicated.
