### ISSUE TITLE
Feature request: Construct windowed CRQA for smaller time series

### ISSUE THREAD

**Issue by a-paxton** [morenococo/crqa#3]
Hi, there,

I'd like to request an update to `wincrqa()` to calculate windowed CRQA using the full reconstructed plot and then subsetting the resulting CRP for datasets that fail the check test: `(embed * delay) > ts1`.

Thanks!

PS: I'm going to try to do this at some point but am not sure if/when I'll get around to it. My intuition is that we could do this by subsetting the full CRP matrix and then inputting that as a way of extracting the relevant CRQA metrics. But maybe that won't work. We'll see!

**Comment by morenococo** [comment]
@a-paxton I see ... maybe we could take the conversation off line, and see what we could do about it.

**Comment by a-paxton** [comment]
Hi, @morenococo—this wasn't intended to be an immediate thing. I'm used to addressing this kind of feature request in an issue just to have it on folks' radar. I'm going to try to address it now!
