### ISSUE TITLE
Improved parsing and checking of function parameters in crqa()

### ISSUE THREAD

**Issue by danm0nster** [morenococo/crqa#6]
In some cases it is possible to pass an invalid option to `crqa()`, but the function will happily run and return output without any warnings or errors.

Example:
```
ts <- rnorm(100)
rqa_result <- crqa(ts, ts, method = "does not exist")
```

We need to parse the input more carefully and produce a warning or error, when something is not as expected.

**Note**: This kind of error can be potentially disastrous if a user mistypes a valid method, because then it is unclear what the function actually does.

**Comment by morenococo** [comment]
thanks for spotting this. Indeed it is a key issue to fix I will directly check it and amend it in the next release of the package.

**Comment by morenococo** [comment]
@danm0nster I fixed this by simply checking that the method exists; otherwise, it stops. I will update this once we gather another couple of the open issues solved.

**Comment by morenococo** [comment]
I included a check for "method", so this issue will not happen anymore
