### ISSUE TITLE
faster plotRP() function

### ISSUE THREAD

**Issue by danm0nster** [morenococo/crqa#9]
The current `plotRP()` is extremely slow.

I have a much faster version based on ggplot that I will add.

Perhaps I can keep the current base plot version, but make it faster too, and add an option, so that the user can select whether to use base plot or ggplot2?

**Comment by morenococo** [comment]
I would say that you can directly change plotRP and leave it only to depend on ggplot2. At the end of the day, it is a visualization function, if it is well-documented and faster, I do not think we need to double that up ...
